name: Go Build and Release

on:
  push:
    branches:
      - '**'
    tags:
      - '*'

jobs:
  build:
    name: Build on ${{ matrix.os }} for ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [amd64, arm64]

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.x'

    - name: Check out code
      uses: actions/checkout@v4

    - name: Build
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          PLATFORM='linux'
        elif [ "${{ matrix.os }}" == "macos-latest" ]; then
          PLATFORM='macos'
        fi
        echo "PLATFORM=$PLATFORM" >> $GITHUB_ENV
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.arch }} go build -ldflags "-s -w -X main.Version=${GITHUB_REF/refs\/tags\//}" -o logviewer-$PLATFORM-${{ matrix.arch }} cmd/logviewer/main.go
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.arch }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: logviewer-$PLATFORM-${{ matrix.arch }}
        path: logviewer-$PLATFORM-${{ matrix.arch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Organize Artifacts into 'bin' Directory
      run: |
        mkdir -p bin
        for subdir in artifacts/*; do
          if [ -d "$subdir" ]; then
            mv "$subdir"/* bin/
          fi
        done

    - name: Create and Upload Release
      uses: softprops/action-gh-release@v1
      with:
        files: bin/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
